### PR TITLE
Print the error

### LINKED ISSUE #60: Print the error when a command fails
I've seen some command failures on a local system and it will be useful to print the error itself, not just a simple error message that the command failed.  This is related to #52 also.

### PR DESCRIPTION
**Pull request by lars-t-hansen**
Fix #60, print the command error when a command fails.  Cron will pick this up and include it in the mailed output.

### CODE REVIEW

**Comment by lars-t-hansen** [comment]
Hm, this looks all wrong, there should be only one commit and two files.  Ignore for now.

**Comment by lars-t-hansen** [comment]
I see what happened.  There are some commits in the history here that are noise, they should not have been merged to main in my fork but are inert since the patches landed separately on the master repo.  This PR actually has only two commits, the one labeled "print the error when the command fails" and the other labeled "remove tabs", which is just formatting.

**Comment by bast** [comment]
Your main branch is ahead of the central main. I have resolved conflicts locally and will push and merge in a moment.

**Comment by bast** [comment]
Hmm. Somehow I accidentally closed the PR. I will push manually to main. Sorry.

**Comment by bast** [comment]
Now the change is in the central repo.

**Pull request closed without merging**
